# Copyright 2025 Sudo Sweden AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockyards-kubevirt
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dockyards-kubevirt
      app.kubernetes.io/part-of: dockyards
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dockyards-kubevirt
        app.kubernetes.io/part-of: dockyards
      name: dockyards-kubevirt
    spec:
      containers:
      - args:
        - --dockyards-namespace=$(METADATA_NAMESPACE)
        env:
        - name: METADATA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: dockyards-kubevirt
        name: dockyards-kubevirt
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: dockyards-registry
      serviceAccountName: dockyards-kubevirt
      securityContext:
        fsGroup: 65532
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
